# Numpy 라이브러리 사용

In [1]:
import numpy as np

## 리스트를 1차원 배열로 전환

In [2]:
a = [1,2,3,4,5]
a_arr = np.array(a)
a_arr

array([1, 2, 3, 4, 5])

## 1차원 배열 생성

In [3]:
b = np.arange(1,6)
b

array([1, 2, 3, 4, 5])

## 1차원 배열을 리스트로 전환

In [4]:
a_list = a_arr.tolist()
a_list

[1, 2, 3, 4, 5]

## 리스트를 2차원 배열로 전환

In [5]:
c = [[1,2], [3,4], [5,6]]
c_arr = np.array(c)
c_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

## 2차원 배열 생성

In [6]:
d = np.arange(1,7).reshape(3,2)
d

array([[1, 2],
       [3, 4],
       [5, 6]])

## 2차원 배열을 리스트로 전환

In [7]:
d_arr = d.tolist()
d_arr

[[1, 2], [3, 4], [5, 6]]

# 배열의 합

In [8]:
a = np.arange(1,6) #(1,2,3,4,5)
b = np.arange(4,9) #(4,5,6,7,8)
print(a+b)

[ 5  7  9 11 13]


## 배열의 곱 (행렬의 곱과는 다른 연산이다.)

In [9]:
a = np.arange(1,6) #(1,2,3,4,5)
b = np.arange(4,9) #(4,5,6,7,8)
print(a*b)

[ 4 10 18 28 40]


# 배열의 차원 확인

In [10]:
a = np.arange(1,5) #(1,2,3,4)
b = np.arange(4,8).reshape(2,2) #([4,5],[6,7])
print(a.shape, a.ndim, b.shape, b.ndim)

(4,) 1 (2, 2) 2


# 배열 요소의 자료형 확인

In [11]:
a = np.arange(1,5) #(1,2,3,4)
b = ['1','2','3','4']
c = [1.1, 2.2, 3.3, 4.4]
b_arr = np.array(b)
c_arr = np.array(c)
print(a.dtype, b_arr.dtype, c_arr.dtype)

int32 <U1 float64


# 브로드캐스팅 (열의 확장) - 크기가 다른 배열의 연산 수행

In [12]:
a = np.arange(1,9).reshape(2,4) #([1,2,3,4],[5,6,7,8])
b = np.arange(1,5) #(1,2,3,4)
print(a+b)

[[ 2  4  6  8]
 [ 6  8 10 12]]


## 브로드캐스팅(행의 확장)

In [13]:
a = np.arange(1,4).reshape(3,1) #([1],[2],[3]) 3행 1열 2차원 벡터
b = np.arange(1,2)
print(a+b)

[[2]
 [3]
 [4]]


## 브로드캐스팅(행, 열의 확장)

In [14]:
a = np.arange(1,4).reshape(3,1) #([1],[2],[3]) 3행 1열 2차원 벡터
b = np.arange(1,4)
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 브로드캐스팅 규칙 - 뒤에서 부터 대응하는 축의 크기가 같거나, 1이어야 함.

In [15]:
a = np.arange(1,7).reshape(3,2)
b = np.arange(1,4)
print(a+b)    #ValueError

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

# 초기화와 동시에 배열 생성

In [ ]:
a = np.zeros(5)
b = np.ones(5)
print(a, a.dtype, b, b.shape)

# 배열의 타입변환

In [ ]:
a = np.arange(1,5) # (1,2,3,4)
b = a.astype('float64')
c = a.astype(float) # 기존 np.float의 접두사?인 np.는 더 이상 이용하지 않는다.
d = c.astype(int)
print(b, c, d)

# 배열 생성 시 타입 지정

In [ ]:
a = np.array([1,2,3], dtype=float)
b = np.array([1.1,2.2,3.3], dtype=int)
print(a, b)

# 배열과 스칼라 간의 연산

In [ ]:
a = np.arange(1,4) #(1,2,3)
print(a-a, a*a, 1/a, a**0.5)

# 색인과 슬라이싱의 특징 - 1) 기존 배열도 함께 변경

In [ ]:
a = np.arange(10) #(0,1,2,3,4,5,6,7,8,9)
print(a[5])

In [ ]:
b = np.arange(10) #(0,1,2,3,4,5,6,7,8,9)
b[3:6] = 10
print(b)

In [ ]:
c = np.arange(10) #(0,1,2,3,4,5,6,7,8,9)
c_arr = c[3:6] #(3,4,5)
c_arr[0] = 777 # 3 -> 777
c_arr[1:] = 888
print(c)

# 색인과 슬라이싱의 특징 - 2) 차원의 변경

In [ ]:
a = np.arange(1,10).reshape(3,3) #[[1,2,3],[4,5,6],[7,8,9]]
a_arr1 = a[1:][:2]
a_arr2 = a[2][2]
print(a_arr1, a_arr2)

In [ ]:
b = np.arange(1,10).reshape(3,3) #[[1,2,3],[4,5,6],[7,8,9]]
b_arr1 = b[1:]
b_arr2 = b_arr1[0]
b_arr3 = b_arr2[0]
print(b_arr1, b_arr2, b_arr3) # 슬라이싱을 적용하지 않는다면 차원이 하나 씩 낮아지는 것을 알 수 있음. 즉, 정수 색인 시 차원 낮아짐.